### ISSUE TITLE
Problems Starting the Sever

### ISSUE THREAD

**Issue by LandonSchropp** [christophercliff/heroku-stripe-checkout#1]
When I try to boot up the server on Heroku, I get the following error:

```
2015-04-19T22:02:50.037052+00:00 app[web.1]: > heroku-stripe-checkout@1.0.0 start /app
2015-04-19T22:02:51.227512+00:00 app[web.1]: npm ERR!
2015-04-19T22:02:51.226168+00:00 app[web.1]: npm ERR! node v0.12.2
2015-04-19T22:02:51.227158+00:00 app[web.1]: npm ERR! heroku-stripe-checkout@1.0.0 start: `node ./`
2015-04-19T22:02:51.219749+00:00 app[web.1]:
2015-04-19T22:02:51.226899+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-04-19T22:02:51.225934+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-04-19T22:02:51.226565+00:00 app[web.1]: npm ERR! npm  v2.7.4
2015-04-19T22:02:51.227311+00:00 app[web.1]: npm ERR! Exit status 1
2015-04-19T22:02:51.232169+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-04-19T22:02:51.227959+00:00 app[web.1]: npm ERR! not with npm itself.
2015-04-19T22:02:51.228094+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-04-19T22:02:51.228233+00:00 app[web.1]: npm ERR!     node ./
2015-04-19T22:02:51.228351+00:00 app[web.1]: npm ERR! You can get their info via:
2015-04-19T22:02:51.228496+00:00 app[web.1]: npm ERR!     npm owner ls heroku-stripe-checkout
2015-04-19T22:02:51.228634+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-04-19T22:02:51.231702+00:00 app[web.1]:
2015-04-19T22:02:51.227817+00:00 app[web.1]: npm ERR! This is most likely a problem with the heroku-stripe-checkout package,
2015-04-19T22:02:51.232046+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-04-19T22:02:51.227615+00:00 app[web.1]: npm ERR! Failed at the heroku-stripe-checkout@1.0.0 start script 'node ./'.
2015-04-19T22:02:51.225367+00:00 app[web.1]: npm ERR! Linux 3.13.0-40-generic
2015-04-19T22:02:52.018962+00:00 heroku[web.1]: State changed from crashed to starting
2015-04-19T22:02:52.018114+00:00 heroku[web.1]: State changed from starting to crashed
2015-04-19T22:02:51.999308+00:00 heroku[web.1]: Process exited with status 1
```

I tried catting `/app/npm-debug.log`, but Heorku says the file doesn't exist.

**Comment by christophercliff** [comment]
Not much info here, but my best guess is an incompatibility with node v0.12.x. This was written for v0.10.x, but I don't think that's specified anywhere. Try https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version.

**Comment by LandonSchropp** [comment]
Thanks for the quick reply! Unfortunately, switching to `0.10.x` didn't help. I can see from the log dump that it's now using `0.10.38`, but I'm still getting the same error.

```
340+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-04-21T02:47:20.961128+00:00 app[web.1]: npm ERR! Failed at the heroku-stripe-checkout@1.0.0 start script.
2015-04-21T02:47:20.961131+00:00 app[web.1]: npm ERR! This is most likely a problem with the heroku-stripe-checkout package,
2015-04-21T02:47:20.961119+00:00 app[web.1]: npm ERR! heroku-stripe-checkout@1.0.0 start: `node ./`
2015-04-21T02:47:20.961907+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-04-21T02:47:20.961132+00:00 app[web.1]: npm ERR! not with npm itself.
2015-04-21T02:47:20.961126+00:00 app[web.1]: npm ERR!
2015-04-21T02:47:20.961456+00:00 app[web.1]: npm ERR!     node ./
2015-04-21T02:47:20.961591+00:00 app[web.1]: npm ERR! You can get their info via:
2015-04-21T02:47:20.962741+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-04-21T02:47:20.962351+00:00 app[web.1]: npm ERR! cwd /app
2015-04-21T02:47:20.965527+00:00 app[web.1]: npm ERR!
2015-04-21T02:47:20.965631+00:00 app[web.1]: npm ERR! Additional logging details can be found in:
2015-04-21T02:47:20.965733+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-04-21T02:47:20.965952+00:00 app[web.1]: npm ERR! not ok code 0
2015-04-21T02:47:20.961696+00:00 app[web.1]: npm ERR!     npm owner ls heroku-stripe-checkout
2015-04-21T02:47:20.962058+00:00 app[web.1]: npm ERR! System Linux 3.13.0-40-generic
2015-04-21T02:47:20.962198+00:00 app[web.1]: npm ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-04-21T02:47:20.962485+00:00 app[web.1]: npm ERR! node -v v0.10.38
2015-04-21T02:47:20.962616+00:00 app[web.1]: npm ERR! npm -v 1.4.28
```

Is there any other information I can provide you with to help debug this? I'm only using test keys on the server, so I'd also be happy to give you access to the server if that would help.

**Comment by christophercliff** [comment]
Looks like there's a bug that's swallowing the stack trace. Can you try running this branch: https://github.com/christophercliff/heroku-stripe-checkout/compare/log-errors

**Comment by LandonSchropp** [comment]
Here's the full deploy log from that branch:

```
2015-04-21T15:53:20.264913+00:00 heroku[api]: Release v9 created by schroppl@gmail.com
2015-04-21T15:53:20.264913+00:00 heroku[api]: Deploy 64b0250 by schroppl@gmail.com
2015-04-21T15:53:20.373480+00:00 heroku[web.1]: State changed from crashed to starting
2015-04-21T15:53:23.337146+00:00 heroku[web.1]: Starting process with command `npm start`
2015-04-21T15:53:25.415334+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-04-21T15:53:25.415305+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-04-21T15:53:26.150070+00:00 app[web.1]: > node ./
2015-04-21T15:53:26.150072+00:00 app[web.1]:
2015-04-21T15:53:26.150060+00:00 app[web.1]:
2015-04-21T15:53:26.150068+00:00 app[web.1]: > heroku-stripe-checkout@1.0.0 start /app
2015-04-21T15:53:27.650091+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND unraveling
2015-04-21T15:53:27.650097+00:00 app[web.1]:     at errnoException (dns.js:44:10)
2015-04-21T15:53:27.650100+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
2015-04-21T15:53:27.690432+00:00 app[web.1]:
2015-04-21T15:53:27.700779+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-04-21T15:53:27.701036+00:00 app[web.1]: npm ERR! node v0.12.2
2015-04-21T15:53:27.701441+00:00 app[web.1]: npm ERR! npm  v2.7.4
2015-04-21T15:53:27.701644+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-04-21T15:53:27.701855+00:00 app[web.1]: npm ERR! heroku-stripe-checkout@1.0.0 start: `node ./`
2015-04-21T15:53:27.702080+00:00 app[web.1]: npm ERR! Exit status 1
2015-04-21T15:53:27.702254+00:00 app[web.1]: npm ERR!
2015-04-21T15:53:27.702508+00:00 app[web.1]: npm ERR! Failed at the heroku-stripe-checkout@1.0.0 start script 'node ./'.
2015-04-21T15:53:27.702670+00:00 app[web.1]: npm ERR! This is most likely a problem with the heroku-stripe-checkout package,
2015-04-21T15:53:27.702911+00:00 app[web.1]: npm ERR! not with npm itself.
2015-04-21T15:53:27.703072+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-04-21T15:53:27.703215+00:00 app[web.1]: npm ERR!     node ./
2015-04-21T15:53:27.703358+00:00 app[web.1]: npm ERR! You can get their info via:
2015-04-21T15:53:27.708212+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-04-21T15:53:27.708354+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-04-21T15:53:27.703519+00:00 app[web.1]: npm ERR!     npm owner ls heroku-stripe-checkout
2015-04-21T15:53:27.707962+00:00 app[web.1]:
2015-04-21T15:53:27.703660+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-04-21T15:53:27.700206+00:00 app[web.1]: npm ERR! Linux 3.13.0-40-generic
2015-04-21T15:53:28.582422+00:00 heroku[web.1]: Process exited with status 1
2015-04-21T15:53:28.597729+00:00 heroku[web.1]: State changed from starting to crashed
2015-04-21T15:53:28.598610+00:00 heroku[web.1]: State changed from crashed to starting
2015-04-21T15:53:30.507298+00:00 heroku[web.1]: Starting process with command `npm start`
2015-04-21T15:53:31.571446+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-04-21T15:53:31.571465+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-04-21T15:53:32.154986+00:00 app[web.1]:
2015-04-21T15:53:32.154993+00:00 app[web.1]: > heroku-stripe-checkout@1.0.0 start /app
2015-04-21T15:53:32.154994+00:00 app[web.1]: > node ./
2015-04-21T15:53:32.154996+00:00 app[web.1]:
2015-04-21T15:53:33.187202+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND unraveling
2015-04-21T15:53:33.222963+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-04-21T15:53:33.222715+00:00 app[web.1]: npm ERR! npm  v2.7.4
2015-04-21T15:53:33.187213+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
2015-04-21T15:53:33.222157+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-04-21T15:53:33.187209+00:00 app[web.1]:     at errnoException (dns.js:44:10)
2015-04-21T15:53:33.222364+00:00 app[web.1]: npm ERR! node v0.12.2
2015-04-21T15:53:33.216793+00:00 app[web.1]:
2015-04-21T15:53:33.223129+00:00 app[web.1]: npm ERR! heroku-stripe-checkout@1.0.0 start: `node ./`
2015-04-21T15:53:33.223260+00:00 app[web.1]: npm ERR! Exit status 1
2015-04-21T15:53:33.221647+00:00 app[web.1]: npm ERR! Linux 3.13.0-40-generic
2015-04-21T15:53:33.227315+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-04-21T15:53:33.227484+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-04-21T15:53:33.223560+00:00 app[web.1]: npm ERR! Failed at the heroku-stripe-checkout@1.0.0 start script 'node ./'.
2015-04-21T15:53:33.223414+00:00 app[web.1]: npm ERR!
2015-04-21T15:53:33.223716+00:00 app[web.1]: npm ERR! This is most likely a problem with the heroku-stripe-checkout package,
2015-04-21T15:53:33.223853+00:00 app[web.1]: npm ERR! not with npm itself.
2015-04-21T15:53:33.223986+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-04-21T15:53:33.224110+00:00 app[web.1]: npm ERR!     node ./
2015-04-21T15:53:33.224257+00:00 app[web.1]: npm ERR! You can get their info via:
2015-04-21T15:53:33.224396+00:00 app[web.1]: npm ERR!     npm owner ls heroku-stripe-checkout
2015-04-21T15:53:33.224541+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-04-21T15:53:33.227006+00:00 app[web.1]:
2015-04-21T15:53:33.934530+00:00 heroku[web.1]: Process exited with status 1
2015-04-21T15:53:33.948212+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by christophercliff** [comment]
I pushed a new build where I committed `node_modules`. Heroku sometimes has problems with npm.
